project:
  type: website
  output-dir: docs

website:
  title: "Joel Parker's Blog"
  navbar:
    right: 
    - about.qmd
    - icon: twitter
      href: https://twitter.com/JoelParker_Stat
    - icon: github
      href: https://github.com/JoelParkerUofA

format:
  html:
    theme: cosmo
    css: styles.css
    bibliography: refernces.bib

editor: visual

